name: Rebuild With New SDK

on:
  push:
    paths-ignore:
      - "**/*.md"
      - '**/*.txt'
  pull_request:
    paths-ignore:
      - "**/*.md"
      - '**/*.txt'
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.event_name  }}
  cancel-in-progress: true

jobs:
  payload-build:
    runs-on: ubuntu-22.04
    steps:

    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Verify x86_64 runner
      run: |
        uname -m
        [ "$(uname -m)" = "x86_64" ] || { echo "ERROR: build requires x86_64 runner"; exit 1; }

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential clang-18 lld-18 xxd yasm nasm python3

    - name: Install toolchain
      run: |
        wget -q https://github.com/ps5-payload-dev/pacbrew-repo/releases/latest/download/ps5-payload-dev.tar.gz
        sudo tar xf ps5-payload-dev.tar.gz -C /

    - name: Build lib (x86_64)
      run: |
        cd lib
        make
        file lib-elf-ps5.a
        cd ..

    - name: Build Payload
      run: |
        export PS5_PAYLOAD_SDK=/opt/ps5-payload-sdk
        bash ci-ps5-kstuff-ldr.sh

    - name: Upload Payload
      uses: actions/upload-artifact@v4
      with:
        name: Payload
        path: ./ps5-kstuff-ldr/kstuff.elf
        if-no-files-found: error
